Repository PKU-Alignment/align-anything, pull requests merged in 2024-09, with the labels that each got.

#65 fix: fix t2t ppo
  align_anything/trainers/text_to_text/ppo.py
  align_anything/trainers/text_to_text/rm.py
Labels: bug

#69 fix: fix llava examples
  README.md
  README_zh-CN.md
  align_anything/configs/template.py
  examples/llava.md
  pyproject.toml
Labels: bug

#72 fix: fix examples, deps, and typos
  .github/ISSUE_TEMPLATE/bug-report.yml
  README.md
  align_anything/configs/template.py
  align_anything/datasets/text_audio_to_text/preference.py
  align_anything/datasets/text_image_to_text/preference.py
  align_anything/datasets/text_image_to_text_image/preference.py
  align_anything/datasets/text_to_audio/preference.py
  align_anything/datasets/text_to_audio/supervised.py
  align_anything/datasets/text_to_image/preference.py
  align_anything/datasets/text_to_image/supervised.py
  align_anything/datasets/text_to_text/preference.py
  align_anything/datasets/text_to_text/prompt_only.py
  align_anything/datasets/text_to_text/supervised.py
  align_anything/datasets/text_to_video/preference.py
  align_anything/evaluation/README.md
  align_anything/evaluation/README_zh-CN.md
  align_anything/utils/multi_process.py
  conda-recipe.yaml
  examples/README.md
  examples/llava.md
  projects/README.md
  pyproject.toml
  scripts/setup.sh
Labels: bug, README

#80 docs: polish readme file
  README.md
Labels: documentation
