Repository PKU-Alignment/align-anything, pull requests merged in 2024-07, with the labels that each got.

#20 docs: polish README and example
  README.md
  README_zh-CN.md
  examples/text_to_image_diffusion.md
Labels: README

#3 feat: add web ui
  README.md
  align_anything/configs/template.py
  align_anything/serve/controller.py
  align_anything/serve/conversation_templates.py
  align_anything/serve/examples/PKU.jpg
  align_anything/serve/examples/boya.jpg
  align_anything/serve/gradio_web_server.py
  align_anything/serve/model_worker.py
  align_anything/utils/constants.py
  pyproject.toml
Labels: enhancement

#21 fix: fix toml dependency
  pyproject.toml
Labels: bug

#28 fix: fix setup.sh
  scripts/setup.sh
Labels: bug
